name: Testing

on:
  pull_request:
    branches: [main]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .
     
    - name: Restore NuGet Packages
      run: nuget restore TestConsole.sln
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Build
      run: msbuild.exe TestConsole.sln /p:Configuration=Release
      
    - name: Run TestConsole Tests
      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe TestConsole.Tests\bin\Release\net46\TestConsole.Tests.dll -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover

    - name: Run TestConsole Tests2
      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe TestConsole.Test2\bin\Release\net46\TestConsole.Test2.dll
      
    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: TestResult.xml
        gist-filename: "code-coverage.json"
        gist-id: "c2e864100c1f49050cb9bd68dbfa40e5"
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
        
    - name: Print code coverage
      run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"

    - name: Print badge data
      run: echo "Badge data ${{steps.test_step.outputs.badge}}"
