name: Testing

on:
  pull_request:
    branches: [main]
    
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
     
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .
     
    - name: Restore NuGet Packages
      run: nuget restore Statclass.sln
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
      
    - name: Build
      run: msbuild.exe TestConsole.sln /p:Configuration=Release
      
    - name: Run TestConosle Tests
      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe TestConsole.Tests\bin\Release\net46\TestConsole.Tests.dll
